# Generated by Django 5.1.4 on 2025-02-19 07:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'العنوان قصير جداً')])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'المحتوى قصير جداً')])),
                ('summary', models.TextField(blank=True, help_text='ملخص قصير للمقال', max_length=300)),
                ('tags', models.CharField(blank=True, help_text='الوسوم مفصولة بفواصل', max_length=500)),
                ('featured_image', models.ImageField(blank=True, help_text='الصورة الرئيسية للمقال', null=True, upload_to='articles/', validators=[myapp.models.validate_image_size])),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('allow_comments', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='عرض في القسم المميز')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'يجب أن يحتوي الاسم على حرفين على الأقل')])),
                ('bio', models.TextField(help_text='نبذة عن الكاتب')),
                ('image', models.ImageField(blank=True, help_text='الحد الأقصى لحجم الصورة 5 ميجابايت', null=True, upload_to='authors/', validators=[myapp.models.validate_image_size])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='الموقع الشخصي للكاتب', null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'كاتب',
                'verbose_name_plural': 'الكتّاب',
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'يومية'), ('weekly', 'أسبوعية'), ('monthly', 'شهرية')], default='weekly', max_length=10)),
                ('subscribed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'اشتراك النشرة البريدية',
                'verbose_name_plural': 'اشتراكات النشرة البريدية',
            },
        ),
        migrations.CreateModel(
            name='ArticleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_progress', models.JSONField(default=dict)),
                ('interaction_data', models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bounce_rate', models.FloatField(default=0)),
                ('avg_time_spent', models.DurationField(blank=True, null=True)),
                ('social_shares', models.JSONField(default=dict)),
                ('device_stats', models.JSONField(default=dict)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='myapp.article')),
            ],
            options={
                'verbose_name': 'تحليلات المقال',
                'verbose_name_plural': 'تحليلات المقالات',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='myapp.author'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='book', help_text='اسم الأيقونة من Bootstrap Icons', max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.category')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='myapp.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'التعليق قصير جداً')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[myapp.models.validate_image_size])),
                ('notification_preferences', models.JSONField(default=dict)),
                ('favorite_articles', models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.article')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_users', to='myapp.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['pub_date', 'status'], name='myapp_artic_pub_dat_9a3616_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='myapp_artic_author__4b9ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='myapp_artic_categor_2d40fd_idx'),
        ),
    ]
