# Generated by Django 5.1.4 on 2025-02-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة المقال', null=True, upload_to='articles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة التصنيف', null=True, upload_to='categories/'),
        ),
    ]
